sudo: false
dist: trusty
language: java

jdk:
- oraclejdk10
- oraclejdk9
- oraclejdk8

script:
  - cd initial && ./gradlew check && cd ..
  - cd documented && ./gradlew check && cd ..
  - cd instrumenting && ./gradlew check && cd ..
  - cd complete && ./gradlew check && cd ..